name: Publish docs via GitHub Pages

on:
  push:
    branches: ["main", "api"]

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies using Poetry
        run: poetry install --only docs
      - name: Deploy docs
        run: poetry run mkdocs gh-deploy
